version: '2.28' # Adjust if needed based on your docker-compose version

services:
  ironshinfightclub_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ironshinadmin
      - POSTGRES_PASSWORD=ironshinfighter
      - POSTGRES_DB=ironshinfightclub
    volumes:
      - ironshinfightclub_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  ironshinfightclub_db:
